### ISSUE TITLE
cumulative test data for groups are NA

### ISSUE THREAD

**Issue by findanna** [finddx/FINDCov19TrackerData#178]
@christophsax @angelicambg can you please check the workflow again?
 `all_cum_tests` in data_all.csv when set is income, region, who_region or world are all NA.

Maybe there is a na.rm missing somewhere?

**Comment by christophsax** [comment]
Not sure if there was reasoning, but we do not calculate cumulative numbers for groups in the summarize functions:

https://github.com/dsbbfinddx/shinyfind/blob/main/R/summarize.R

So these values are not shown here as well:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/1390827/158479431-74eccf45-67d5-45f9-9906-48227cd1bb35.png">

**Comment by dsbb-finddx** [comment]
I see cumulative values for groups. This is strange.
<img width="1309" alt="Screenshot 2022-03-15 at 23 06 39" src="https://user-images.githubusercontent.com/62348391/158480467-1f502b74-39df-43ca-b455-5eb0e3af1035.png">

**Comment by christophsax** [comment]
Yeah, I see your version as well, as soon as I am running the full app, rather than the subapp.

@benubah can you help us? In dsbbfinddx/shinyfindapps@e5e600d8d9cc743ca18b37da7a700fdc44bc8d6d, you removed the `shinyfind::` prefix. This seems to cause the different behavior. Any idea why? I don't see an alternative function definition, very strange. When I set a browser everything looks the same - but is is also late.

I think `shinyfind::summarize_over_group()` is right. All aggregations everywhere in the workflow should always use the functions in https://github.com/dsbbfinddx/shinyfind/blob/main/R/summarize.R, there should be no exception.

**Comment by christophsax** [comment]
@dsbb-finddx if you make me an admin of this repo, I could add Ben as a collaborator. Alternatively, you can add Ben as a collaborator yourself.

**Comment by dsbb-finddx** [comment]
> @dsbb-finddx if you make me an admin of this repo, I could add Ben as a collaborator. Alternatively, you can add Ben as a collaborator yourself.

Done, added him as a collaborator :)

**Comment by benubah** [comment]
> @benubah can you help us? In [dsbbfinddx/shinyfindapps@e5e600d](https://github.com/dsbbfinddx/shinyfindapps/commit/e5e600d8d9cc743ca18b37da7a700fdc44bc8d6d), you removed the `shinyfind::` prefix. This seems to cause the different behavior. Any idea why? I don't see an alternative function definition, very strange. When I set a browser everything looks the same - but is is also late.
> 

 The removed prefix had been restored several weeks ago in `main`  here: https://github.com/dsbbfinddx/shinyfindapps/blob/main/map/R/server.R#L91 and https://github.com/dsbbfinddx/shinyfindapps/commit/7674ce1604c7327b30c1a373ca9568b2fa23795e
 
 I can't reproduce the problem yet when running from the `main` branch.  The current version of `main` is deployed here: https://finddx.shinyapps.io/shinyfindapps_dev/ for further checks possibly

**Comment by benubah** [comment]
About the differences between my `dev` link and production, I reminded @dsbb-finddx some days back that we've not yet deployed the current version of `main` to production and it seems that they are aware and wanted it that way at that time for some reason. So if we deploy `main` to production, the numbers should match.
>
> But I thought we should have shinyfind::summarize_over_group() as well. That gave my runs yesterday the same result in the > sub-app and in the full app.

The current version of `main` works for me both in the full app and sub-app. But I'll add the prefix as you suggested

**Comment by christophsax** [comment]
Thanks. That sounds good and resolves most of the confusion. I may have overlooked last night something else, but with `shinyfind::summarize_over_group()` we are confident what to expect.

Which brings us back to the original topic: `shinyfind::summarize_over_group()` does not produce cummulative numbers for groups. @dsbb-finddx was this something we overlooked or that we did conciously.

I guess we can extend `shinyfind::summarize_over_group()` easily (sum of for non per capita, mean for per capita measures). The two `summarize_over_` funcitons should return the same columns in the same order. @benubah can you give a try on a branch and make sure the shiny app still works afterwards?

If the function is extended successfully, `data_shiny.csv` should see values for cumulative values as well.

**Comment by dsbb-finddx** [comment]
> Thanks. That sounds good and resolves most of the confusion. I may have overlooked last night something else, but with `shinyfind::summarize_over_group()` we are confident what to expect.
> 
> Which brings us back to the original topic: `shinyfind::summarize_over_group()` does not produce cummulative numbers for groups. @dsbb-finddx was this something we overlooked or that we did conciously?
I am not sure we did it consciously. But I think we were focusing on the `shinyfind::summarise_over_time()` function where cumsum values don't make sense. 

> 
> I guess we can extend `shinyfind::summarize_over_group()` easily (sum of for non per capita, mean for per capita measures). The two `summarize_over_` funcitons should return the same columns in the same order. @benubah can you give a try on a branch and make sure the shiny app still works afterwards?
> 
> If the function is extended successfully, `data_shiny.csv` should see values for cumulative values as well.

Is it `data_shiny.csv` or `data_all.csv`?

Please give it a go and then we should follow up extensively with a QC, comparing numbers before we push to prod.

**Comment by benubah** [comment]
> I guess we can extend shinyfind::summarize_over_group() easily (sum of for non per capita, mean for per capita measures).               
> The two summarize_over_ funcitons should return the same columns in the same order. @benubah can you give a try on a 
> branch and make sure the shiny app still works afterwards?
>

@christophsax  something like this?  https://github.com/dsbbfinddx/shinyfind/blob/missing-cum-numbers/R/summarize.R#L155-L163

I'm quite confused comparing the numbers for groups (income, who_region, etc) in `data_all.csv` and the table in DATA DEEP DIVE sub-app. The cumulative numbers for groups in `data_all.csv` are in the `all_cum_` and `cap_cum_` format, while in the table we have `avg_all_new_` , `sum_cap_new_` , `avg_cap_new_` and `sum_cap_new_`

To understand clearly, should `all_cum_`  and `cap_cum_` in `data_all` be equal to what in the table (in Data Deep Dive)?

**Comment by christophsax** [comment]
These should be the same as the normal `cap` caculations:

```
      cap100k_cum_cases      = all_cum_cases / pop_100k,
      cap100k_cum_deaths     = all_cum_deaths / pop_100k,
      cap100k_cum_tests      = all_cum_tests / pop_100k,
```

E.g., `mean(cap100k_cum_tests, na.rm = TRUE)`

**Comment by christophsax** [comment]
Alls variables should be as defined in: (https://github.com/dsbbfinddx/shinyfind/blob/main/inst/codebook/codebook_extended.csv).

In data all, for historical reasons, I removed the `avg_` prefix and dropped the `sum` calculations. So I would say `avg_cap_new_` is the same as `cap_new_`.

Around here: https://github.com/dsbbfinddx/FINDCov19Tracker/blob/feb064ee7c8a89f8248061d58864485f4b852b4e/R/shiny-data.R#L273

Does that make sense?

**Comment by benubah** [comment]
Thanks!  

Adjusted `cap100k_cum_` here: https://github.com/dsbbfinddx/shinyfind/commit/0d5b54e6e65cf0b792c3cf551d8e41f8cba89851

https://github.com/dsbbfinddx/shinyfind/commit/0d5b54e6e65cf0b792c3cf551d8e41f8cba89851

> To understand clearly, what should `all_cum_` and `cap_cum_` in data_all be equal to what in the table (in Data Deep Dive)?
>

To site an example: for `who_region` group, what should `all_cum_` and `cap_cum_` in `data_all.csv` be equal to in the table (in Data Deep Dive) below?

![image](https://user-images.githubusercontent.com/11357251/159187896-11e60089-65b7-4684-a409-c48e01c74bc2.png)

**Comment by christophsax** [comment]
You need to figure that out from the code. These are your lines:

https://github.com/dsbbfinddx/shinyfindapps/blob/2db9142acf35dd8ea5620010c60207fc2e79d03e/map/R/server.R#L54-L59

**Comment by christophsax** [comment]
@benubah are we done here?

**Comment by benubah** [comment]
The changes are pushed for review here: https://github.com/dsbbfinddx/shinyfind/pull/27

**Comment by benubah** [comment]
We no longer have NA values for cumulative data
