### ISSUE TITLE
Impact of change of name for the organisation

### ISSUE THREAD

**Issue by findanna** [finddx/FINDCov19TrackerData#181]
Hello all,
I would like to change the name of the organisation on github.
Before I do that I am aware that this change might impact some of the github actions and workflows currently in place, so I would need to ask for your approval and your suggestions on moving this forward.

The name change needs to be completed this week.
In case you need to have a call to organise and find out exactly where the impact will be please let me know.

**Comment by angelicambg** [comment]
Hello @findanna 

Generally, it won't create many problems, ["GitHub automatically redirects references to your repositories"](https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization) so that give us some time to update the references that included old organization's name (for instance links to download data). Related to the Github actions we should update the steps for package installation, and that can be done once the name changes.

It would be good to coordinate when the organization name will change, so we can have some time to reply in case something breaks.

**Comment by findanna** [comment]
Thank you @angelicambg! 
Can I then proceed today?

**Comment by angelicambg** [comment]
yes, sure!

I can see 8 repos in the organization. Are those all repositories, or are there more private related to the tracker?

**Comment by findanna** [comment]
> yes, sure!
> 
> I can see 8 repos in the organization. Are those all repositories, or are there more private related to the tracker?

There are more private repos, not related to the tracker. @christophsax can you please confirm I can proceed with changing the name of the organisation? You have a better visual since you are member of the org.

**Comment by christophsax** [comment]
Yes, sorry. I overlooked this, I thought Angelica did arleady confirm. We have the following private repositories:

```
<img width="513" alt="image" src="https://user-images.githubusercontent.com/1390827/161362106-9669a1fd-7d16-4f1d-aa1c-1c3a49a792af.png">
```

Any critical ones that we are not affiliated?

From Angelica's link, it sounds as this is not problematic. I would do it at a point where we have some time to react. First half of next week is good for me. So if you rename on Monday, we have the following days to fix unforeseen problems.

**Comment by christophsax** [comment]
Goal is to rename late on Monday, April 11.

**Comment by findanna** [comment]
Just changed name to finddx. Hope nothing breaks :)

**Comment by benubah** [comment]
Will watch out

**Comment by angelicambg** [comment]
Links with the former organisation's name are being redirected correctly. However, I already changed the organisation name for the following repositories:

- [FINDCov19TrackerData](https://github.com/finddx/FINDCov19TrackerData)
- [FINDCov19Tracker](https://github.com/finddx/FINDCov19Tracker)
- [FINDCov19TrackerDataQC](https://github.com/finddx/FINDCov19TrackerDataQC)
- [shinyfind](https://github.com/finddx/shinyfind) I don't have permission to update, so I created a pull request.

@benubah could you change the organisation's name for the shinyapps repositories?
