### ISSUE TITLE
New Zealand positivity rate is too high

### ISSUE THREAD

**Issue by findanna** [finddx/FINDCov19TrackerData#182]
@angelicambg @seawaR can you please check the source and scraping for New Zealand? 
Current positivity rates on the tracker are really high (500%)

**Comment by seawaR** [comment]
Hello @findanna,

We didn't find any problems with the scraping. However, since the beginning of March cases have spiked and the current level of cases is above the level of tests.
![data_NZ](https://user-images.githubusercontent.com/9646737/160845814-dbab2b57-1264-4f19-9d4e-0c0b16e65d6c.png)
