### ISSUE TITLE
Suspicious data for India series - Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#188]
Hi Team,

We have observed that the value published for India on the file "[coronavirus_tests.csv](https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv)" for the period 04/14/2022 seems extreme in comparison with other historical values.
Could you please confirm that the value is correct and provide the reason for such a big jump?

Thank you in advance

Best regards,
Mariia

**Comment by findanna** [comment]
Hello @DataOps-epam,

There is indeed a big jump.
We have scraped 830810157 total number of tests on 2022-04-14, which is the officially reported cumulative value for India on their [website](https://www.icmr.gov.in/) as well.
However their official number  SAMPLES TESTED ON APRIL 13, 2022 is 434877, which would make the total to: 795389402.
Will contact them and see where the mistake is. 
Will keep you updated.

**Comment by findanna** [comment]
We have contacted them but no news yet from their side. 
@benubah @seawaR is it possible to scrape the daily number of tests for India for the time being, until they correct the cumulative ones?
Please start correcting from 2022-04-14 adding 434877 to the previous cumulative value and keep on with the daily values from then onwards.

**Comment by benubah** [comment]
I am of the opinion that the excessive increase in numbers on 2022-04-14 was as a result of additional data included (**reconciled by the states**) into the cumulative sum (on that day) as indicated in the underlined NOTE in the screenshot below. It seems they just added some previously missing data to the cumulative on that particular day.

![image](https://user-images.githubusercontent.com/11357251/164213553-3239d6f0-5a79-4457-bd4f-95b8c924a3d0.png)

The scraping works well and logs the daily data correctly afterwards.

**Comment by findanna** [comment]
Thank you @benubah. I agree with you then, please keep as it is. @DataOps-epam we will keep the cumulative value as stated in the source for 2022-04-14, until further news.

**Comment by DataOps-epam** [comment]
Hi Team,

Thank you for the information provided, this is very useful for us.
