### ISSUE TITLE
Suspicious data for Singapore total amount of cases

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#191]
Hi, 

Could you please advise if you have any info regarding big data change for Singapore Cumulative Number Of Performed CV Tests from 19108195 to 62418583 as of 05/16/2022?

Thank you.

**Comment by benubah** [comment]
Thanks for the report.

The [source](https://www.moh.gov.sg/covid-19/statistics) updated their `Number of Reportable ART Swabs Tested` i.e., antigen rapid tests, on  05/16/2022. They seem to do this update once in a while and not every single day.

![image](https://user-images.githubusercontent.com/11357251/169077625-78813258-86e4-4ceb-a7a5-a2ebbc0ad078.png)
