### ISSUE TITLE
Extreme jump for Australia: Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#192]
Hi Team,

Could you please check the below measure as we see noticed an extremely high jump for 6/6/2022? Numbers jumped from 72163238 on 06/05/2022 to 142981490 the next day.

Series: Australia: Cumulative Number Of Performed CV Tests

Source Link: https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv

Could you advise on this?

 Thank You.

**Comment by findanna** [comment]
@DataOps-epam thank you for reporting this.
It seems like a scraping error has occurred, we will fix this in due time.
@benubah @seawaR please correct value for Australia as per [source](https://www.health.gov.au/health-alerts/covid-19/case-numbers-and-statistics#total-tests-and-results), which currently shows 72,380,675 total number of tests as per 2022-06-07.

**Comment by benubah** [comment]
On it, thanks!

**Comment by benubah** [comment]
This is fixed for 2022-06-06 and before. #193 fixes it for today. And a [fix](https://github.com/finddx/FINDCov19TrackerData/commit/0201dadaa21b45164dca789d058077b04273ac4e) has been pushed for the scraping error - let's see how it resolves tomorrow

**Comment by findanna** [comment]
Thank you very much @benubah!
Let's keep an eye on Australia then :)
