### ISSUE TITLE
Indonesia: Cumulative number of performed CV tests

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#195]
Hi,
Check please the data for Indonesia: Cumulative number of performed CV tests  tests_cumulative_corrected column for 12/07/2022 period.
![image](https://user-images.githubusercontent.com/80464515/178591797-5ef0be3f-3e66-42a3-9875-382ce283cf0e.png)

**Comment by seawaR** [comment]
There was a small issue with the date but the correction should be visible now.

**Comment by benubah** [comment]
Thanks! All fixed
