### ISSUE TITLE
Mismatch with Brazil official data for Cumulative number of performed CV tests

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#196]
Hi,

Could you please check data for Brazil Cumulative number of performed CV tests for 08/17/2022 period?
We observe data on the source is 78641767: http://www.giscard.com.br/coronavirus/indice-testes-realizados-covid19-brasil.php

While in your file it was adjusted to 70923215. Could you please advise what is the reason of mismtach?

Thank you.

**Comment by benubah** [comment]
Many thanks for this observation! It's fixed now!
