### ISSUE TITLE
Issue with Cumulative Number Of Performed CV Tests for most countries 

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#198]
Hi Team,

Could you please check the below measures as we see noticed suspicious revisions for all of them with today's release,

Source Link: https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv

Could you advise on this?

Series :

Argentina:   Cumulative number of performed CV tests
Australia: Cumulative number   of performed CV tests
Brazil: Cumulative number of   performed CV tests
Bulgaria: Cumulative number of   performed CV tests
Canada: Cumulative number of   performed CV tests
Chile: Cumulative number of   performed CV tests
Colombia: Cumulative number of   performed CV tests
Czechia: Cumulative number of   performed CV tests
Ecuador: Cumulative number of   performed CV tests
France: Cumulative number of   performed CV tests
Germany: Cumulative number of   performed CV tests
Greece: Cumulative number of   performed CV tests
Hong Kong: Cumulative number   of performed CV tests
Indonesia: Cumulative number   of performed CV tests
Ireland: Cumulative number of   performed CV tests
Japan: Cumulative number of   performed CV tests
Korea, Republic of: Cumulative   number of performed CV tests
Malaysia: Cumulative number of   performed CV tests
Mexico: Cumulative number of   performed CV tests
Netherlands: Cumulative number   of performed CV tests
New Zealand: Cumulative number   of performed CV tests
Peru: Cumulative number of   performed CV tests
Philippines: Cumulative number   of performed CV tests
Poland: Cumulative number of   performed CV tests
Portugal: Cumulative number of   performed CV tests
Russian Federation: Cumulative   number of performed CV tests
Saudi Arabia: Cumulative   number of performed CV tests
Singapore: Cumulative number   of performed CV tests
South Africa: Cumulative   number of performed CV tests
Sweden: Cumulative number of   performed CV tests
Switzerland: Cumulative number   of performed CV tests
Thailand: Cumulative number of   performed CV tests
Turkey: Cumulative number of   performed CV tests
UK: Cumulative number of   performed CV tests
Venezuela, Bolivarian Republic   of: Cumulative number of performed CV tests

 Thank You.

**Comment by benubah** [comment]
Thanks for reporting this!

Yes, there seems to be something suspicious with the `tests_cumulative_corrected` column of the dataset for these countries. We're taking close at this and will report back soon.

**Comment by findanna** [comment]
> https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv

@benubah please revert to previous version of file, so that the tracker does not show these values.

**Comment by benubah** [comment]
okay

**Comment by benubah** [comment]
> @benubah please revert to previous version of file, so that the tracker does not show these values.

I've reverted for now. Still taking a look at the cause with @seawaR

**Comment by benubah** [comment]
After the workflow run this evening, the numbers seem to be correct again. We will watch the workflow a few more times tomorrow before finalizing on this.

**Comment by benubah** [comment]
We have monitored this closely in the past few days and the issue is now resolved.

**Comment by DataOps-epam** [comment]
Yes, Thank you for your help.
