### ISSUE TITLE
Indonesia: Cumulative number of performed CV tests

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#201]
Hi team, 

We have found suspicious data for the following period 9/19/2022 due to largest jump in the history for Indonesia: Cumulative number of performed CV tests. Could you please check the data for the following series?

**Comment by DataOps-epam** [comment]
Hi team,
Have you had a chance to review the incident below?

**Comment by benubah** [comment]
Yes, have taken a look - there was a scraping error. Pushed a fix now!

**Comment by benubah** [comment]
Thanks for reporting this! The issue is completely resolved now! You may want to take a look at: https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv
