### ISSUE TITLE
France: Cumulative number of performed CV tests - Issue

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#203]
Hi team,

We are facing some suspicious revisions when checking the data provided and what we see on our end on the test_cumulative_corrected column for the dataset of the country of France.
Could you please advise if these are correct?

**Comment by findanna** [comment]
@DataOps-epam thank you very much for your feedback, indeed there seems to be a problem with France data, which changed values back from 2021-02-19 onwards. @benubah @seawaR can you please look into this urgently?

**Comment by benubah** [comment]
On it! Thanks!

**Comment by benubah** [comment]
I see a large negative value for France: `France,2021-02-21,-44849342,4830416,France,https://dashboard.covid19.data.gouv.fr/suivi-des-tests?location=Frau,0,49679758`

From this date onwards, the numbers are incorrect.

Will try to fix

**Comment by findanna** [comment]
@benubah yes I think it might be a scraping error? Currently cumulative number of tests in the [french portal](https://dashboard.covid19.data.gouv.fr/suivi-des-tests?location=Frau) is 272 775 929

**Comment by benubah** [comment]
Yes, the error was just introduced yesterday. It has been correct all along till yesterday. I see that it was correct on 2022-10-17 here: https://raw.githubusercontent.com/finddx/FINDCov19TrackerData/3d1c857ee3502b2215fcfa7b0905ce33602d0750/processed/coronavirus_tests.csv

**Comment by benubah** [comment]
@seawaR corrected the negative value and the problem is fixed: https://raw.githubusercontent.com/finddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv
