### ISSUE TITLE
Czechia - Cumulative number of performed CV tests - Issue

### ISSUE THREAD

**Issue by DataOps-epam** [finddx/FINDCov19TrackerData#204]
Hi team,

We are facing some suspicious revisions when checking the data provided and what we see on our end on the cumulative number of performed CV tests column for the dataset of the country of France.
Could you please advise if these are correct?

**Comment by benubah** [comment]
Thanks for reporting this. Found the problem for Czechia and implementing a fix for this right away.

**Comment by benubah** [comment]
The problem with Czechia is fixed now
