### ISSUE TITLE
Correct new tests for Czech Republic  from 11.02.2023

### ISSUE THREAD

**Issue by findanna** [finddx/FINDCov19TrackerData#206]
Hello, 
@angelicambg @seawaR can you please correct asap?

![Screenshot 2023-02-20 at 16 12 14](https://user-images.githubusercontent.com/62348391/220143416-66146ff3-fafe-4d85-9350-572510135c85.png)

**Comment by seawaR** [comment]
Hi @findanna,

The correction was made yesterday with the manual updates.
